import pyautogui
import time
import keyboard

time.sleep(3)

pyautogui.press('win')
time.sleep(1)
pyautogui.typewrite('Dragonboy_vn_v230')
time.sleep(1)
pyautogui.typewrite('.exe')
time.sleep(1)
pyautogui.press('enter')
time.sleep(6)
pyautogui.press('enter')
time.sleep(6)
pyautogui.press('enter')
time.sleep(1)
pyautogui.press('f1')
time.sleep(1)
pyautogui.press('right')
time.sleep(1)
pyautogui.press('right')
time.sleep(1)
pyautogui.press('right')
time.sleep(1)
pyautogui.press('down')
time.sleep(1)
pyautogui.press('right')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
keyboard.press('alt')
keyboard.press('f4')
keyboard.release('alt')
keyboard.release('f4')
time.sleep(3)

while 1:
    pyautogui.press('win')
    time.sleep(1)
    pyautogui.typewrite('Dragonboy_vn_v230')
    time.sleep(1)
    pyautogui.typewrite('.exe')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(6)
    pyautogui.press('enter')
    time.sleep(20)
    pyautogui.press('enter')
    time.sleep(1)
    pyautogui.press('f1')
    time.sleep(1)
    pyautogui.press('right')
    time.sleep(1)
    pyautogui.press('right')
    time.sleep(1)
    pyautogui.press('right')
    time.sleep(1)
    pyautogui.press('down')
    time.sleep(1)
    pyautogui.press('right')
    time.sleep(1)
    pyautogui.press('enter')
    time.sleep(1)
    keyboard.press('alt')
    keyboard.press('f4')
    keyboard.release('alt')
    keyboard.release('f4')
    time.sleep(3)
    

